spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/kynpost
    username: kynpostgres
    password: kynpostgrespw
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 6379
    r2dbc:
      repositories:
        enabled: true
logging:
  level:
    # Set root logging level to INFO
    root: INFO
    # Set specific package logging levels if needed
    com.kyn.user: INFO
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
    org.springframework.r2dbc: DEBUG
    org.springframework.data.r2dbc: DEBUG
server:
  port: 8080

jwt:
  secret: afa3ae3cd6a86723abbf3b11bb031a1750a71879efa01ba6cd34bc8e29688835